### ISSUE TITLE
Titlebar button animations become janky while the effect is activated

### ISSUE THREAD

**Issue by zlotny** [a-parhom/LightlyShaders#1]
Expected behaviour (LightlyShaders de-activated on Desktop Effects):
https://user-images.githubusercontent.com/6155245/140564350-5632db4f-eb23-45ea-83e5-8e8ae5ff25a8.mp4

Actual behaviour:
https://user-images.githubusercontent.com/6155245/140564362-142b74a7-1098-4f1b-a3db-04090bc8cf79.mp4

Windows out of focus won't show the hover effect while active ones do it with a lot of jankyness. I've uploaded the 2 videos at 60fps so it's more noticeable.

I know this fork is a hack to try to circumvent _The Glitch_ but I wanted to let you know.

Also, as a bonus, the hack is easily noticeable on windows like Peek :)
![image](https://user-images.githubusercontent.com/6155245/140564620-02b9323d-665f-4803-843d-6106540ccaad.png)

Anyhow, thanks for the effort on trying to solve this!

**Comment by a-parhom** [comment]
I've tried to workaround the problem with Peek. Not perfect, because small shadows in bottom corners are still visible, but much better than before. Don't know if it is possible to fix that completely using this approach of moving shadows under the window.

I couldn't figure out the cause of the titlebar problem yet, but I hope I'll find it and fix it in a few days.

**Comment by zlotny** [comment]
Thanks for patching the issue with Peek! Seems fixed now.

I've realized that the issue with the titlebar is related to updating all the titlebar, not only the buttons. If you put a window in and out of focus (like alt-tabbing between 2 of them) it takes a while to update the title bar.

**Comment by a-parhom** [comment]
Please try to pull recent changes from the master branch and reinstall the plugin.

Now it uses absolutely different approach and tries to kind of interpolate the shadows in the cut out regions, without shrinking the shadows. Also, it doesn't call paintWindow() multiple times now.

The issue #2 theoretically should also be fixed now.

**Comment by zlotny** [comment]
Damn! It's really good now! At this point I don't know if you should contact @Luwx even if the original repo is marked as read-only. I'll use this from now on and I'll let you know if I encounter some other unexpected behaviour.

Thank you so much for putting work in this!

**Comment by a-parhom** [comment]
Well, it's still kind of "hacky hack" that can break on different settings, themes, CSD windows etc., not a "right" solution. And as Luwx states in his last commit, the "right" solution is impossible with Plasma >=5.23.
