### ISSUE TITLE
LightlyShaders broken ?

### ISSUE THREAD

**Issue by ramon501** [a-parhom/LightlyShaders#100]
i updated plasma to 5.27.4 and the effect seems to be broken, recompiling it did not work, not sure if i am the only one

**Comment by FLYISFOOL** [comment]
I'm having the same issue.

**Comment by a-parhom** [comment]
Can't reproduce.

**Comment by ramon501** [comment]
I just tried to recompile it and it worked this fine (both LightlyShaders and another effect i have) and both worked fine this time

**Comment by FLYISFOOL** [comment]
After I upgrad to the latest manjaro testing version released on April 14th just now, I recompiled lightyshders and it works fine now.
