### ISSUE TITLE
Effect broken

### ISSUE THREAD

**Issue by ramon501** [a-parhom/LightlyShaders#102]
It doesnt seem to be working with plasmashell 5.27.5, can you take a look ?

**Comment by Blovien** [comment]
I can confirm, the effect doesn't show in the desktop effects, same version of plasma shell.

**Comment by a-parhom** [comment]
Duplicate of #29

**Comment by ramon501** [comment]
at least to me it doesnt work even after recompiling it, i keep getting this error:
AutoMoc warning
---------------
"SRC:/lightlyshaders.cpp"
includes the moc file "lightlyshaders.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_CLASS, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

**Comment by ramon501** [comment]
ok i got it working today after updating cmake it seems
