### ISSUE TITLE
v2.0 not rounding corners on Plasma 5.26.1

### ISSUE THREAD

**Issue by mak0226** [a-parhom/LightlyShaders#103]
I installed this using the instructions in the README, and enabled it in settings, but no corners are rounded. I also tried disabling other effects. I'm using Sierra Breeze Enhanced window decorations, and my computer supports OpenGL 4.6. Thanks in advance.

**Comment by ramon501** [comment]
Effect works for me, i am using the master branch and not the branch v2.0

**Comment by a-parhom** [comment]
Please make sure you are using the right Lightlyshaders version with the righr Plasma version. Also make sure you selected No borders in window decoration settings.
