### ISSUE TITLE
All programs will have a transparent right angle

### ISSUE THREAD

**Issue by jcfun** [a-parhom/LightlyShaders#104]
Although LightlyShaders is in effect. But all programs will have a transparent right angle:
![image](https://github.com/a-parhom/LightlyShaders/assets/58456995/08d229fb-c24a-431e-ba84-08b8312aa224)
My device:
![image](https://github.com/a-parhom/LightlyShaders/assets/58456995/b8a0ee68-1313-4f49-bb8e-a24c1958d5e1)

**Comment by a-parhom** [comment]
Are you on Wayland with blur effect enabled?

**Comment by a-parhom** [comment]
Oh, I see its X11. That's weird. Looks like some kind of misconfiguration. Could you provide some more screenshots as well as your config for window decoration and lightlyshaders itself?

**Comment by levy-deng** [comment]
I have the same issue. I can upload those things as well.

**Comment by levy-deng** [comment]
turning blur off removes the small corner. Is there some other blur effect that will not cause the right angle?

**Comment by a-parhom** [comment]
This effect relies on window decoration for fixing "korner bug" on top corners. You can try my other project https://github.com/a-parhom/RoundedSBE which has a window decoration integrated with the corner rounding effect.

**Comment by a-parhom** [comment]
The new branch plasma6 includes a forked and modified blur effect, so the issue should be fixed with Plasma 6 release.
