### ISSUE TITLE
Window contents rounding?

### ISSUE THREAD

**Issue by ErrorNoInternet** [a-parhom/LightlyShaders#105]
Is there a way to fix this effect?
![image](https://github.com/a-parhom/LightlyShaders/assets/61157623/6b31015e-8e9a-4072-bbd6-db7ce89000bb)
There is a very sharp edge inside the window
![image](https://github.com/a-parhom/LightlyShaders/assets/61157623/dd0c976c-46eb-4377-9731-97c8d8fff6bc)

**Comment by a-parhom** [comment]
Looks like you are using borders in your window decoration settings. This effect should be used with No borders option selected.

**Comment by ErrorNoInternet** [comment]
Thanks :) that fixed it.
