### ISSUE TITLE
Kwin Wayland crashes when all monitors turned off

### ISSUE THREAD

**Issue by Goodname15** [a-parhom/LightlyShaders#106]
I am using KDE 5.27.6 in Fedora Linux 38 and have recompiled and reinstalled LightlyShaders multiple times.

When using LightlyShaders in a Wayland session, turning off both of my monitors (which means having no output) causes Kwin to crash. After that, only my primary monitor is actually usable since dragging a window to the second screen crashes Kwin once more. Only then will Kwin stay stable regardless of action until I turn off my monitors again.

**Comment by a-parhom** [comment]
Is this still an issue with v2.2.1?

**Comment by Goodname15** [comment]
So I‘ve tested it too and it now seems to not crash but I haven’t quite understood the new issue with it. After turning on the monitors again it seems to have some sort of Korners bug where it still keeps the rounding but has transparency behind it. 

Also it did seem to cause some sort of instability last time I tried which caused flickering for me.

I don’t know if these new issues are related though, so maybe it should be in a new issue, if so, this one can be closed as the crashing seems to be resolved.

**Comment by RomanKode** [comment]
> So I‘ve tested it too and it now seems to not crash but I haven’t quite understood the new issue with it. After turning on the monitors again it seems to have some sort of Korners bug where it still keeps the rounding but has transparency behind it. 
> 
> Also it did seem to cause some sort of instability last time I tried which caused flickering for me.
> 
> I don’t know if these new issues are related though, so maybe it should be in a new issue, if so, this one can be closed as the crashing seems to be resolved.

We can open a new issue for lightlyshader(not the rounded blur effect) loosing the rounded corners when turning off and on the monitor.

**Comment by Goodname15** [comment]
The described issue has now been opened under #121 making this one complete.
