### ISSUE TITLE
Minimized windows look blurred

### ISSUE THREAD

**Issue by SkyLissh** [a-parhom/LightlyShaders#108]
I installed it on Fedora 38 KDE Plasma 5.27.7

I built the master branch without issue, but when the LightlyShaders desktop effect is activated all the minimized windows look very blurred, I'm using scaling at 125%
![image](https://github.com/a-parhom/LightlyShaders/assets/72633267/012ba1e4-c74c-44dc-8836-0921a2db0119)

**Comment by a-parhom** [comment]
This should be fix in Plasma 6. You can try plasma6 branch with it.
