### ISSUE TITLE
Fail install.sh

### ISSUE THREAD

**Issue by ben2talk** [a-parhom/LightlyShaders#114]
```
sudo ./install.sh
pread: Inappropriate ioctl for device
grep: warning: stray \ before /
libkwin.so.5 library not found, exiting...

```

**Comment by a-parhom** [comment]
Does executing `sudo updatedb` before running the script help?

**Comment by ben2talk** [comment]
Ah, thank you so much.

**Comment by hirad1986** [comment]
I have the same issue and `sudo updatedb` didn't help, using Arch.

**Comment by a-parhom** [comment]
You can find libkwin.so.5 file manually and make a symlink libkwin.so to it in the directory, where ld looks for libraries to link with.

**Comment by hirad1986** [comment]
Thanks. That worked.
