### ISSUE TITLE
Building error on KDE 5.27.10: libkwin.so.5 library not found, exiting...

### ISSUE THREAD

**Issue by wokawoka** [a-parhom/LightlyShaders#115]
I am trying to upgrade from version 2.2.0 (that I installed last week) to 2.2.1 on KDE 5.27.10 and I' m receiving the following error:
```
Looking for libkwin.so.5 location...
libkwin.so.5 library not found, exiting...
```
I have read in the changelog that an installer script which makes a symlink to libkwin.so.5 was introduced, but apparently it doesn't work on my setup.
Any idea?
Thank you!

**Comment by a-parhom** [comment]
Try to find libkwin.so.5 file manually and make a symlink named libkwin.so to it in the same directory. After that you can install like in previous versions.

**Comment by wokawoka** [comment]
Thank you for your answer.
I have found libkwin.so.5 in /usr/lib/x86_64-linux-gnu/ but in that directory libkwin.so is already there and it's already pointing to libkwin.so.5 . 
Any suggestion?
Thank you very much again

**Comment by a-parhom** [comment]
Then you can build with cmake and install:
`mkdir build; cd build`
`cmake ../ -DCMAKE_INSTALL_PREFIX=/usr`
`make -j$(nproc)`
`sudo make install`

**Comment by a-parhom** [comment]
Also, before installing this version, use the uninstall script to remove the previous one.

**Comment by wokawoka** [comment]
It did work.
I thought I had to use the install script.
Thank you
