### ISSUE TITLE
All windows are just white squares

### ISSUE THREAD

**Issue by Faithxull** [a-parhom/LightlyShaders#116]
I'm on Arch
Plasma Version : 5.27.10
Framework Version: 5.114.0
Qt Version : 5.15.12

After Installing LightlyShaders i logged out and logged back in and now all the windows are completely white.

![Screenshot_20240206_221404](https://github.com/a-parhom/LightlyShaders/assets/130126011/18a2c7b9-4411-4326-9b94-914de7703d6f)

**Comment by Faithxull** [comment]
its a really old laptop with an Intel i3-380m processor and integrated graphics

for drivers I just use the default drivers
I'm not sure which exact one I will check once I get home

Note: Games like minecraft run without any graphical issues. I've also installed lightlyshaders once on a different installation of arch on the same laptop and it worked fine that time

**Comment by Faithxull** [comment]
Okay im using the i915 kernel driver

**Comment by a-parhom** [comment]
I see, looks like a bug in v110 shader. Unfortunately, I can't test it right now. As soon as I'll get access to my old laptop, that uses v110 shader, I'll try to fix that.
