### ISSUE TITLE
widget error during compilation

### ISSUE THREAD

**Issue by DarlesChickens1** [a-parhom/LightlyShaders#117]
![image](https://github.com/a-parhom/LightlyShaders/assets/113041723/ebf2c1d5-a33f-44a9-ab7f-75967638d720)
I installed all the dependencies, but the script did not work for me. I also manually symlinked libkwin.so to libkwin.so.5 but `sudo make install` still throws the error 
`‘widget’ was not declared in this scope; did you mean ‘QWidget’?`

Is this an error on my end or is anyone else getting this as well? I am on Debian (installed today).

**Comment by a-parhom** [comment]
What Plasma version do you have?

**Comment by DarlesChickens1** [comment]
![image](https://github.com/a-parhom/LightlyShaders/assets/113041723/82789b97-eec7-4dcb-afdb-7492dfc39296)
Sorry for not including enough info, I hope this helps

**Comment by a-parhom** [comment]
You need Plasma 5.27.10 to use version 2.2. With 5.27.5 you can use v2.1 of LightlyShaders.
