### ISSUE TITLE
Use it without shadows.

### ISSUE THREAD

**Issue by Nikita-Presnov** [a-parhom/LightlyShaders#12]
Hello
Is it possible to use it only with outline around window, without shadows?
Judging by the writing, this would greatly save resources. 

Also, the frame for some reason is returned for an inactive open window, I know that this bug has existed for a long time.

**Comment by a-parhom** [comment]
The purpose of this fork was to fix the "korners" bug by restoring the shadows. So disabling the shadow restoration is not the priority, at least for now. Though you can try the latest changes from the master branch, the performance of the plugin was improved. Or you can use some other fork and just disable blur and/or shadows.

And what do you mean by "the frame is returned for inactive window"? Could you send a screenshot?

**Comment by a-parhom** [comment]
@Nikita-Presnov Did you try the latest changes from master branch? Does the performance issue and the issue with inactive windows persist?

**Comment by a-parhom** [comment]
Thank you. So closing now.
