### ISSUE TITLE
Windows are very dark with HDR enabled

### ISSUE THREAD

**Issue by Kevadroz** [a-parhom/LightlyShaders#123]
![Captura de pantalla_20240308_134610](https://github.com/a-parhom/LightlyShaders/assets/16049149/31d47b85-32de-4fb2-b9e9-ca2be5f5f0cd)

**Comment by Kivarnis** [comment]
Can confirm

**Comment by NICHOLAS85** [comment]
May be related but I had an issue where windows went extremely dark, but not black, when using a custom ICC color profile. Enabling HDR without the profile did not give me any black windows.

**Comment by matinlotfali** [comment]
This is fixed in https://github.com/matinlotfali/KDE-Rounded-Corners

**Comment by NICHOLAS85** [comment]
![Screenshot_20240503_131005](https://github.com/a-parhom/LightlyShaders/assets/15698885/aeb66320-2585-45e4-858e-9a576c65a84c)

**Comment by NICHOLAS85** [comment]
Can confirm your repo works with ICC profiles and after some configuration looks quite similar to what I had with LightlyShaders. Thanks for sharing!

![Screenshot_20240503_131005](https://github.com/a-parhom/LightlyShaders/assets/15698885/618ddcf6-5ad3-4a6b-85a7-2f014e4d2328)

**Comment by a-parhom** [comment]
Should be fixed in plasma6 branch.
