### ISSUE TITLE
Albert launcher is virtually unresponsive with LightlyShaders enabled (Plasma 6.0.2, Wayland, Arch w/ CachyOS packages)

### ISSUE THREAD

**Issue by FezzedOne** [a-parhom/LightlyShaders#127]
As the title suggests. Whenever I attempt to invoke [Albert](https://github.com/albertlauncher) with the Lightly shaders (and blur variant) enabled, Albert renders at around 0.5 FPS, which is (obviously) unusably slow. System is fully up to date as of a few minutes ago and I'm using Plasma packages from the CachyOS repo. The vanilla Plasma blur isn't enabled, and no other application behaves this way — the rest of the desktop remains perfectly responsive. When I disable the Lightly effects and then restart Albert (and also Plasma), Albert becomes responsive again, even when I re-enable the effects *after* Albert is restarted.

**Comment by FezzedOne** [comment]
**Update:** Albert just became fully responsive again after a few minutes of waiting. `journalctl -b 0 | grep 'albert'` (new log entries):
```log
Mar 14 04:34:33 fezzedone-MSI systemd[11684]: Started albert show.
Mar 14 04:34:33 fezzedone-MSI kwin_wayland_wrapper[17820]: Albert set visible.
```
Nothing from Lightly though. This has happened before. Whenever I log in, Albert apparently ends up becoming very slow and unresponsive for a few minutes, then mysteriously becomes responsive after several minutes have passed, with no relevant log info explaining what happened. I didn't touch Albert's configuration at all, and I already had disabled Albert's file indexing before this login to rule that out.

**Comment by meisaamayako** [comment]
Is that an issue with Albert on other themes or specifically when LightlyShaders is enabled? Try disabling or removing LightlyShaders and test it again, this might a problem with Albert and not a-parhom's work.

**Comment by FezzedOne** [comment]
Just found out the issue was actually [caused by an NVIDIA driver bug](https://bbs.archlinux.org/viewtopic.php?id=293400) that also caused kernel freezes several minutes after waking up my laptop from sleep. When I removed the bugged drivers for a test, Albert was immediately responsive as expected even with the shaders enabled. And after the latest 550.x driver update today, the issue now seems to be fully resolved (and most likely also the kernel freezing issue that I at first assumed was unrelated).
