### ISSUE TITLE
Corners are not rounded if they are covered by a transparent window

### ISSUE THREAD

**Issue by ryu-ketsueki** [a-parhom/LightlyShaders#13]
![Flameshot_20220115_181311](https://user-images.githubusercontent.com/39316730/149637907-a748c079-1705-4b43-81bf-786aa161d0f2.png)
![Flameshot_20220115_181301](https://user-images.githubusercontent.com/39316730/149637909-6de603a4-2617-45ba-a16c-b070044efb45.png)

I noticed this when I saw how Firefox didn't get its bottom corners rounded because of how Latte dock's render area was covering the corners but when I opened Peek to record it, I noticed it happens with any window, even the ones that are transparent. Probably there is no easy fix for that without undoing the performance improvements.

**Comment by ryu-ketsueki** [comment]
#11

**Comment by a-parhom** [comment]
That's intended, because the plugin processes now only areas that are not covered by anything to gain some more performance. I think, I can make this behavior configurable though.

**Comment by a-parhom** [comment]
Try to build from master with latest changes.

**Comment by ryu-ketsueki** [comment]
They're back. Hope that didn't affect the performance improvements too much
