### ISSUE TITLE
Disappeared From Desktop Effects - Plasma

### ISSUE THREAD

**Issue by akano12** [a-parhom/LightlyShaders#141]
Hello, i updated plasma to 6.0.5 today and after rebooting, the option to toggle lightlyshaders from Desktop Effects is no longer available. Tried uninstalling/reinstalling AUR package and option still missing from the Desktop Effects.

OS: Arch Linux
DE: Plasma 6.0.5
WM: kwin

**Comment by matinlotfali** [comment]
Give me some time to try it on an arch virtual machine.

**Comment by ThatcherChen** [comment]
I encountered the same problem.

**Comment by 0x4c756e61** [comment]
If you updated from 5.27 this is expected behavior, plasma5 effects need to be ported over to plasma6, there's a development branch for now but no release as far as I know

**Comment by akano12** [comment]
> If you updated from 5.27 this is expected behavior, plasma5 effects need to be ported over to plasma6, there's a development branch for now but no release as far as I know

Plasma 5 has nothing to do with this, this happened after updating from 6.0.4 to 6.0.5

**Comment by akano12** [comment]
> > Hello, i updated plasma to 6.0.5 today and after rebooting, the option to toggle lightlyshaders from Desktop Effects is no longer available. Tried uninstalling/reinstalling AUR package and option still missing from the Desktop Effects.
> > 
> > OS: Arch Linux DE: Plasma 6.0.5 WM: kwin
> 
> Recompilation solves this problem.

Can you please assist in the building process? It fails no matter what i do.
