### ISSUE TITLE
cannot build on ubuntu 22.04

### ISSUE THREAD

**Issue by grav3yardshawty** [a-parhom/LightlyShaders#148]
trying to build on ubuntu 22.04 returns this:

- Could NOT find KF5GuiAddons , checked the following files:
    /usr/lib/x86_64-linux-gnu/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (version 5.92.0)
    /lib/x86_64-linux-gnu/cmake/KF5GuiAddons/KF5GuiAddonsConfig.cmake (version 5.92.0)

CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KF5 (missing: Config ConfigWidgets CoreAddons Crash
  GlobalAccel I18n KIO Service Init Notifications Service WidgetsAddons
  WindowSystem GuiAddons) (Required is at least version "5.102.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:93 (find_package_handle_standard_args)
  CMakeLists.txt:44 (find_package)
  
  when trying to install dependencies people with similar issues suggest, my system tells me i have the latest versions already. i thought i had to update like part of the error suggests, but again, latest versions.
  
  i am on plasma 5.24.7, is my system just not updated enough to install this version of lightly?

**Comment by InkstainTheBat** [comment]
Hello. Was this actually resolved? If so how? I'm facing a similar issue on an Ubuntu derivative (Linux Mint 21.3)

**Comment by grav3yardshawty** [comment]
> Hello. Was this actually resolved? If so how? I'm facing a similar issue on an Ubuntu derivative (Linux Mint 21.3)

I’m not sure if our issue is the exact same, but in my case my plasma version actually was just too old. after updating to plasma 5.27.11 through kubuntu backports and installing some dependencies i was able to build it fine
