### ISSUE TITLE
deepin

### ISSUE THREAD

**Issue by IT-Tagore** [a-parhom/LightlyShaders#17]
-- Could NOT find XCB_RENDER (missing: XCB_RENDER_LIBRARY XCB_RENDER_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_SHAPE (missing: XCB_SHAPE_LIBRARY XCB_SHAPE_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XFIXES (missing: XCB_XFIXES_LIBRARY XCB_XFIXES_INCLUDE_DIR XCB_RENDER_FOUND XCB_SHAPE_FOUND) (found version "")
-- Could NOT find XCB_SHM (missing: XCB_SHM_LIBRARY XCB_SHM_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_ATOM (missing: XCB_ATOM_LIBRARY XCB_ATOM_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_AUX (missing: XCB_AUX_LIBRARY XCB_AUX_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_COMPOSITE (missing: XCB_COMPOSITE_LIBRARY XCB_COMPOSITE_INCLUDE_DIR XCB_XFIXES_FOUND) (found version "")
-- Could NOT find XCB_CURSOR (missing: XCB_CURSOR_LIBRARY XCB_CURSOR_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_DAMAGE (missing: XCB_DAMAGE_LIBRARY XCB_DAMAGE_INCLUDE_DIR XCB_XFIXES_FOUND) (found version "")
-- Could NOT find XCB_DPMS (missing: XCB_DPMS_LIBRARY XCB_DPMS_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_DRI2 (missing: XCB_DRI2_LIBRARY XCB_DRI2_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_DRI3 (missing: XCB_DRI3_LIBRARY XCB_DRI3_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_EVENT (missing: XCB_EVENT_LIBRARY XCB_EVENT_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_EWMH (missing: XCB_EWMH_LIBRARY XCB_EWMH_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_GLX (missing: XCB_GLX_LIBRARY XCB_GLX_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_ICCCM (missing: XCB_ICCCM_LIBRARY XCB_ICCCM_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_IMAGE (missing: XCB_IMAGE_LIBRARY XCB_IMAGE_INCLUDE_DIR XCB_SHM_FOUND) (found version "")
-- Could NOT find XCB_KEYSYMS (missing: XCB_KEYSYMS_LIBRARY XCB_KEYSYMS_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_PRESENT (missing: XCB_PRESENT_LIBRARY XCB_PRESENT_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_RANDR (missing: XCB_RANDR_LIBRARY XCB_RANDR_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_RECORD (missing: XCB_RECORD_LIBRARY XCB_RECORD_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_RENDERUTIL (missing: XCB_RENDERUTIL_LIBRARY XCB_RENDERUTIL_INCLUDE_DIR XCB_RENDER_FOUND) (found version "")
-- Could NOT find XCB_RES (missing: XCB_RES_LIBRARY XCB_RES_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_SCREENSAVER (missing: XCB_SCREENSAVER_LIBRARY XCB_SCREENSAVER_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_SYNC (missing: XCB_SYNC_LIBRARY XCB_SYNC_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_UTIL (missing: XCB_UTIL_LIBRARY XCB_UTIL_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XEVIE (missing: XCB_XEVIE_LIBRARY XCB_XEVIE_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XF86DRI (missing: XCB_XF86DRI_LIBRARY XCB_XF86DRI_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XINERAMA (missing: XCB_XINERAMA_LIBRARY XCB_XINERAMA_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XKB (missing: XCB_XKB_LIBRARY XCB_XKB_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XPRINT (missing: XCB_XPRINT_LIBRARY XCB_XPRINT_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XTEST (missing: XCB_XTEST_LIBRARY XCB_XTEST_INCLUDE_DIR) (found version "")
-- Could NOT find XCB_XV (missing: XCB_XV_LIBRARY XCB_XV_INCLUDE_DIR XCB_SHM_FOUND) (found version "")
-- Could NOT find XCB_XVMC (missing: XCB_XVMC_LIBRARY XCB_XVMC_INCLUDE_DIR XCB_XV_FOUND) (found version "")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tiger/Desktop/LightlyShaders/qt5build
[  7%] Automatic MOC for target kwin4_lightlyshaders_config
[ 15%] Built target kwin4_lightlyshaders_config_autogen
[ 69%] Built target kwin4_lightlyshaders_config
[ 76%] Automatic MOC for target kwin4_effect_lightlyshaders
AutoMoc warning
---------------
  "/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp"
The file includes the moc file "lightlyshaders.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON, K_PLUGIN_CLASS_WITH_JSON, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[ 76%] Built target kwin4_effect_lightlyshaders_autogen
[ 84%] Building CXX object CMakeFiles/kwin4_effect_lightlyshaders.dir/lightlyshaders.cpp.o
In file included from /home/tiger/Desktop/LightlyShaders/dbus.h:5,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:20:
/home/tiger/Desktop/LightlyShaders/lightlyshaders.h:42:10: warning:   by ‘void KWin::LightlyShadersEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’ [-Woverloaded-virtual]
     void prePaintWindow(EffectWindow* w, WindowPrePaintData& data, std::chrono::milliseconds time);
          ^~~~~~~~~~~~~~
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp: In member function ‘void KWin::LightlyShadersEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’:
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:323:46: error: no matching function for call to ‘KWin::EffectsHandler::prePaintWindow(KWin::EffectWindow*&, KWin::WindowPrePaintData&, std::chrono::milliseconds&)’
         effects->prePaintWindow(w, data, time);
                                              ^
In file included from /home/tiger/Desktop/LightlyShaders/lightlyshaders.h:23,
                 from /home/tiger/Desktop/LightlyShaders/dbus.h:5,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:20:
/usr/include/kwineffects.h:837:18: note: candidate: ‘virtual void KWin::EffectsHandler::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, int)’
     virtual void prePaintWindow(EffectWindow* w, WindowPrePaintData& data, int time) = 0;
                  ^~~~~~~~~~~~~~
/usr/include/kwineffects.h:837:18: note:   no known conversion for argument 3 from ‘std::chrono::milliseconds’ {aka ‘std::chrono::duration<long int, std::ratio<1, 1000> >’} to ‘int’
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:364:42: error: no matching function for call to ‘KWin::EffectsHandler::prePaintWindow(KWin::EffectWindow*&, KWin::WindowPrePaintData&, std::chrono::milliseconds&)’
     effects->prePaintWindow(w, data, time);
                                          ^
In file included from /home/tiger/Desktop/LightlyShaders/lightlyshaders.h:23,
                 from /home/tiger/Desktop/LightlyShaders/dbus.h:5,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:20:
/usr/include/kwineffects.h:837:18: note: candidate: ‘virtual void KWin::EffectsHandler::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, int)’
     virtual void prePaintWindow(EffectWindow* w, WindowPrePaintData& data, int time) = 0;
                  ^~~~~~~~~~~~~~
/usr/include/kwineffects.h:837:18: note:   no known conversion for argument 3 from ‘std::chrono::milliseconds’ {aka ‘std::chrono::duration<long int, std::ratio<1, 1000> >’} to ‘int’
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp: In member function ‘virtual void KWin::LightlyShadersEffect::paintWindow(KWin::EffectWindow*, int, QRegion, KWin::WindowPaintData&)’:
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:391:24: error: ‘class KWin::EffectWindow’ has no member named ‘frameGeometry’; did you mean ‘iconGeometry’?
     const QRect geo(w->frameGeometry());
                        ^~~~~~~~~~~~~
                        iconGeometry
In file included from /usr/include/x86_64-linux-gnu/qt5/QtDBus/qtdbusglobal.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/qdbusabstractadaptor.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/QDBusAbstractAdaptor:1,
                 from /home/tiger/Desktop/LightlyShaders/dbus.h:4,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:20:
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp: In member function ‘void KWin::LightlyShadersEffect::fillRegion(const QRegion&, const QColor&)’:
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:537:41: warning: ‘QVector<QRect> QRegion::rects() const’ is deprecated: Use begin()/end() instead [-Wdeprecated-declarations]
     foreach (const QRect & r, reg.rects())
                                         ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qmatrix.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qtransform.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qimage.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QImage:1,
                 from /usr/include/kwinglobals.h:25,
                 from /usr/include/kwineffects.h:29,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.h:23,
                 from /home/tiger/Desktop/LightlyShaders/dbus.h:5,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:20:
/usr/include/x86_64-linux-gnu/qt5/QtGui/qregion.h:125:20: note: declared here
     QVector<QRect> rects() const;
                    ^~~~~
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp: In member function ‘QList<KWin::GLTexture> KWin::LightlyShadersEffect::getTexRegions(KWin::EffectWindow*, const QRect*)’:
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:558:61: error: invalid user-defined conversion from ‘int’ to ‘const QString&’ [-fpermissive]
             sample_tex.append(GLTexture(GL_TEXTURE_RECTANGLE));
                                                             ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/qtdbusglobal.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/qdbusabstractadaptor.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/QDBusAbstractAdaptor:1,
                 from /home/tiger/Desktop/LightlyShaders/dbus.h:4,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:20:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:830:31: note: candidate is: ‘QString::QString(const char*)’ <near match>
     inline QT_ASCII_CAST_WARN QString(const char *ch)
                               ^~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:830:31: note:   conversion of argument 1 would be ill-formed:
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:558:61: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
             sample_tex.append(GLTexture(GL_TEXTURE_RECTANGLE));
                                                             ^
/home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:558:61: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qvarlengtharray.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qmetatype.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/qtdbusglobal.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/qdbusabstractadaptor.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtDBus/QDBusAbstractAdaptor:1,
                 from /home/tiger/Desktop/LightlyShaders/dbus.h:4,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:20:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:830:51: note:   initializing argument 1 of ‘QString::QString(const char*)’
     inline QT_ASCII_CAST_WARN QString(const char *ch)
                                       ~~~~~~~~~~~~^~
In file included from /usr/include/kwinglutils.h:28,
                 from /home/tiger/Desktop/LightlyShaders/lightlyshaders.cpp:29:
/usr/include/kwingltexture.h:59:14: note:   initializing argument 1 of ‘KWin::GLTexture::GLTexture(const QString&)’
     explicit GLTexture(const QString& fileName);
              ^~~~~~~~~
make[2]: *** [CMakeFiles/kwin4_effect_lightlyshaders.dir/build.make:63：CMakeFiles/kwin4_effect_lightlyshaders.dir/lightlyshaders.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:270：CMakeFiles/kwin4_effect_lightlyshaders.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2

**Comment by a-parhom** [comment]
Deepin is not officially supported since it uses its own KWin fork. That siad, did you make sure to install all needed dependencies? Just try to find deepin packages corresponding to ones, mentioned in README.

**Comment by Hibanaw** [comment]
The same problem.
If you don't care the shadow problem at the corners, try this binary file, a cutefish plugin called roundedwindows compiled under deepin: https://bbs.deepin.org/en/post/226223

**Comment by a-parhom** [comment]
Since this is a dependency issue, I'll close it.
