### ISSUE TITLE
Maximized windows eventually become rounded again

### ISSUE THREAD

**Issue by jsebean** [a-parhom/LightlyShaders#20]
As the title describes, for me, as I toggle through windows, maximized windows will become rounded again despite "Disable for Maximized windows" option is enabled. While initially the window will no longer be rounded, it will become rounded again over time, usually after tabbing through windows/changing the stack of windows.

**Comment by a-parhom** [comment]
Thank you for your report. I'll try to fix that, maybe in a couple of days.

**Comment by a-parhom** [comment]
Please, try the latest changes.

**Comment by SqrHornet** [comment]
It's better now, but closed maximized windows become rounded when they're reopened.

**Comment by a-parhom** [comment]
There is no windowMaximizedStateChanged event emmitted if the the window is opened already maximized, as well as I haven't found any other way in KWin to verify that the window is maximized. So probably this just can't be fixed and you'll have to unmaximize and maximize the window again, sorry.

**Comment by a-parhom** [comment]
Actually, it seems that I've found a solution, eventually. Please, try the latest commit.

**Comment by SqrHornet** [comment]
As far as I tried, now it works top-notch

**Comment by a-parhom** [comment]
Thank you! Closing now.
