### ISSUE TITLE
Some coners go balck after resume from maximized

### ISSUE THREAD

**Issue by Hibanaw** [a-parhom/LightlyShaders#21]
Steam for example,
also once met in wechat, a no-border wine app.
![image](https://user-images.githubusercontent.com/61813396/151692486-60e79d71-6abd-4230-8fbb-a746ba6f4505.png)

**Comment by a-parhom** [comment]
Did it happen before yesterday changes in master?

**Comment by Hibanaw** [comment]
> Did it happen before yesterday changes in master?

Oh, sorry, I haven't update to the latest at the time
Close now and I will reopen the issue if it reproduces

**Comment by a-parhom** [comment]
It may be connected with steam using some kind of opengl rendering that is causing those glitches, so feel free to reopen.

**Comment by Hibanaw** [comment]
![image](https://user-images.githubusercontent.com/61813396/151693626-38721eb9-d32c-4077-94a4-6c8ab65d913d.png)
Can be reproduced in the latest version
netease-cloud-music in aur
Sometimes it's fine, and sometimes it reproduces

**Comment by YidaozhanYa** [comment]
This problem didn't happen at commit 0b80af, but it happened in later versions

**Comment by a-parhom** [comment]
This should be fixed now.
