### ISSUE TITLE
Effect is applied to JetBrains application context menus

### ISSUE THREAD

**Issue by KristianOde** [a-parhom/LightlyShaders#25]
With the latest master this happens in Goland context menus:
![image](https://user-images.githubusercontent.com/46893137/152150008-6e055d08-d9b7-4eb6-8a57-a6a87eea1a4b.png)
I haven't really tested this with the other JetBrains IDE's but I assume it's the same there. As far as I know these applications are the only situations where this happens, presumably because it uses a different method to display context menus than most other apps. I just noticed this after updating to the latest master branch yesterday. Previously I had been using the `performance_optimization` branch for a while because it had been working perfectly, but it was uninstalled for some reason after updating my system.

Also alongside this I have an issue with the effect not applying to random windows, but the issue seems more random than it previously was when I had a similar issue. I'm suspecting it has something to do with auto-tiling of windows (I use Bismuth tiling script) but I honestly have no idea.

**Comment by a-parhom** [comment]
Please, try the latest changes. Feel free to reopen if the issue persists.

**Comment by KristianOde** [comment]
The effect is still applied to the context/right click menus but they no longer have the corner issues at least, so that's a big improvement. The menus are usually completely square and unaffected by any KDE/GTK styling so I feel like LightlyShader shouldn't affect it either, but it looks better with it applied so I'm content. Thanks.

**Comment by a-parhom** [comment]
I've tested this on Android Studio, which is also based on JetBrains IDE and the issue was completely resolved. Looks like Goland uses different window names for menus. I'll install it and check. Maybe, in a few days.

**Comment by a-parhom** [comment]
Please, try latest changes.
