### ISSUE TITLE
When maximizing a window, bottom corners aren't rounded

### ISSUE THREAD

**Issue by hellojaccc** [a-parhom/LightlyShaders#27]
![Screenshot_20220204_165330](https://user-images.githubusercontent.com/71537512/152492309-cc7b4937-b2f1-4557-ac0c-df0b4f209c34.png)

Not only Vivaldi window, it also happen on other apps

**Comment by Hibanaw** [comment]
The effect doesn't seem to work when there's window animation.

**Comment by a-parhom** [comment]
This plugin is not compatible with animations.
