### ISSUE TITLE
Bottom corners not rounded since the last update

### ISSUE THREAD

**Issue by thrdroom** [a-parhom/LightlyShaders#29]
Since the last system update the bottom corners aren't rounded any more.
Running latest KDE Neon 5.24 User Edition

![grafik](https://user-images.githubusercontent.com/5912061/153689071-0f1f99b8-ae98-4037-ae31-3b9a3d25896f.png)

**Comment by thrdroom** [comment]
Reinstalling did the trick. Is there way to implement a process into the Shaders that does this fix automatically on every update?

**Comment by a-parhom** [comment]
After Plasma updates the effect needs to be recompiled. Closing, as it's not an issue.
