### ISSUE TITLE
Square Artifacts in Application Corners

### ISSUE THREAD

**Issue by cachandlerdev** [a-parhom/LightlyShaders#33]
**Summary**

Little squares appear in the corner of an application when another app is placed on top of it.

**Steps to reproduce**

Turn on LightlyShaders.
Open an application.
Open another app, and place it on top of one of the first app's corners.
Move the second app off the first one's corners
See a square artifact in the corner.

**Current behaviour (bug)**

Little square artifacts can be seen in the corners of an application window if another app is placed on top of it and then removed.

**Expected behaviour (correct)**

The artifacts would not be visible.

**Relevant logs and/or media (optional)**

https://user-images.githubusercontent.com/70250943/153778517-521fb1de-3ea3-4f27-8f02-4e96952dcf9c.mp4

**Software/Os Versions**

Operating System: Manjaro Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.16.5-1-MANJARO (64-bit)
Graphics Platform: X11

**Comment by a-parhom** [comment]
That's intended behaviour, the effect does not process corners that are under another another window to gain performance. It  is expected that you use opaque or blured theme.

**Comment by cachandlerdev** [comment]
I'm not sure I understand what you mean by an opaque or blurred theme. Although I'm not sure if this would be technically feasible, wouldn't it make more sense to process corners as soon as they're visible, rather than a couple seconds afterwards? As is, these white corner artifacts sometimes appear for several seconds before vanishing.

**Comment by a-parhom** [comment]
I mean that when you move a window it becomes transparent. That's the cause you are seeing the unprocessed corners under it.

The problem with corners not being processed immediately after becoming visible is known.  Something to do with the process of calculating the hidden areas of a window, but I haven't found a solution yet.

**Comment by a-parhom** [comment]
The behavior when moving or resizing a window should improve now.

**Comment by a-parhom** [comment]
If I have understand the problem correctly, the artifacts should also be gone.
