### ISSUE TITLE
Effect gone after reboot

### ISSUE THREAD

**Issue by coffseducation** [a-parhom/LightlyShaders#35]
LightlyShaders works great - but after a reboot the effect is gone and the setting is absent in Desktop Effects.
Deleting the files and re-installing works but how to make it persistent across reboots?
Thanks!

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.24.1
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-28-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

**Comment by a-parhom** [comment]
Did you update your plasma before the reboot? The plugin may need to be recompiled after some Plasma updates (which 5.24.1 is). Otherwise it should persist after each reboot.

**Comment by coffseducation** [comment]
Ok, must be the updates. Thanks.

**Comment by coffseducation** [comment]
re-opening sorry!

The effect not working after reboot continues to persist.
