### ISSUE TITLE
I know the Ukraine situation, but all the files is gone and how do i build it?

### ISSUE THREAD

**Issue by nguyensang28** [a-parhom/LightlyShaders#37]
There's nothing in this repository, i know that situation but i just want to use this rounded corner style

**Comment by nguyensang28** [comment]
> After he removed the code, I downloaded the code using a bug on the GitHub homepage and created a backup of this repo. you can get it from here: https://github.com/YidaozhanYa/LightlyShaders

thanks for keeping the code

**Comment by a-parhom** [comment]
After we will have fought back russian invaders, I'll can return to solving your issues, friends.
I'm sorry for removing the code, but I've done that to attract your attention to our situation.
If you want me to return to working on LightlyShaders as soon as possible, you can support Ukrainian army financially:

To help in USD:

BENEFICIARY: National Bank of Ukraine
BENEFICIARY BIC: NBUA UA UX
BENEFICIARY ADDRESS: 9 Instytutska St, Kyiv, 01601, Ukraine
ACCOUNT NUMBER: 400807238
BENEFICIARY BANK NAME: JP MORGAN CHASE BANK, New York
BENEFICIARY BANK BIC: CHASUS33
ABA 0210 0002 1
BENEFICIARY BANK ADDRESS: 383 Madison Avenue, New York, NY 10017, USA
PURPOSE OF PAYMENT: for crediting account 47330992708

To help in EUR:

BENEFICIARY: National Bank of Ukraine
BENEFICIARY’S ACCOUNT: UA843000010000000047330992708
BENEFICIARY’S BANK: National Bank of Ukraine
CORRESPONDENT ACCOUNT: IBAN DE05504000005040040066
CORRESPONDENT BANK: DEUTSCHE BUNDESBANK, Frankfurt
SWIFT CODE: MARKDEFF

To help in GBP:

BENEFICIARY/RECIPIENT NAME: National Bank of Ukraine
SORT CODE: 60-92-42 
ACCOUNT NUMBER: GB52CHAS60924280033041
REFERENCE FOR CREDITING ACCOUNT: 47330992708
BENEFICIARY BIC: NBUA UA UX
BENEFICIARY ADDRESS: 9 Instytutska St, Kyiv, 01601, Ukraine
BENEFICIARY BANK NAME: JP MORGAN CHASE BANK NA, London
BENEFICIARY BANK BIC: CHASGB2L
BENEFICIARY BANK ADDRESS: 125 London Wall, London EC2Y 5AJ, UK

To help in CHF:
BENEFICIARY: National Bank of Ukraine
BENEFICIARY BIC: NBUA UA UX
BENEFICIARY ADDRESS: 9 Instytutska St, Kyiv, 01601, Ukraine
ACCOUNT NUMBER: 0700-01227572
IBAN CH32 0070 0070 0012 2757 2 
BENEFICIARY BANK NAME: ZURCHER KANTONALBANK, ZURICH
BENEFICIARY BANK BIC: ZKBKCHZZ80A
BENEFICIARY BANK ADDRESS: Josefstrasse 222, 8005 Zurich, Switzerland
PURPOSE OF PAYMENT: for crediting account 47330992708 

To help in AUD:
BENEFICIARY: National Bank of Ukraine
BENEFICIARY BIC: NBUA UA UX
BENEFICIARY ADDRESS: 9 Instytutska St, Kyiv, 01601, Ukraine
ACCOUNT NUMBER: 81753-2
BENEFICIARY BANK NAME: RESERVE  BANK OF AUSTRALIA, Sydney
BENEFICIARY BANK BIC: RSBKAU2S
BENEFICIARY BANK ADDRESS: GPO Box 3947, Sydney NSW 2000, Australia
PURPOSE OF PAYMENT: for crediting account 47330992708

To help in CNY:
BENEFICIARY: National Bank of Ukraine
BENEFICIARY BIC: NBUA UA UX
BENEFICIARY ADDRESS: 9 Instytutska St, Kyiv, 01601, Ukraine
ACCOUNT NUMBER: 447-0-946243-6
BENEFICIARY BANK NAME: STANDARD CHARTERED BANK, Hong Kong
BENEFICIARY BANK BIC: SCBLHKHH
BENEFICIARY BANK ADDRESS: GPO Box  21, Hong Kong
PURPOSE OF PAYMENT: for crediting account 47330992708

To help in CAD:
BENEFICIARY: National Bank of Ukraine
BENEFICIARY BIC: NBUA UA UX
BENEFICIARY ADDRESS: 9 Instytutska St, Kyiv, 01601, Ukraine
ACCOUNT NUMBER: 3144-1044-166
BENEFICIARY BANK NAME: BANK OF MONTREAL, Toronto
BENEFICIARY BANK BIC: BOFMCAM2
BENEFICIARY BANK ADDRESS: 100 King Street West, 24th Floor, Toronto, Ontario, M5X 1A1, Canada
PURPOSE OF PAYMENT: for crediting account 47330992708

To help in JPY:
BENEFICIARY: National Bank of Ukraine
BENEFICIARY BIC: NBUA UA UX
BENEFICIARY ADDRESS: 9 Instytutska St, Kyiv, 01601, Ukraine
ACCOUNT NUMBER: 653-0430048
BENEFICIARY BANK NAME: MUFG BANK LTD, Tokyo
BENEFICIARY BANK BIC: BOTK JP JT
BENEFICIARY BANK ADDRESS: 1-2-3, Nihombashi HONGOKU-CHO, Chuo-ku, Tokyo 1003 -0021 Japan
PURPOSE OF PAYMENT: for crediting account 47330992708

**Comment by Hibanaw** [comment]
I am sorry about the situation in Ukraine,
Also sorry about the unfriendly voices from Chinese netizens.
For well-known reasons, it is difficult and unsafe for Chinese citizens to donate to the Ukrainian government, so I bought the Polish game "War of Mine" from various sources to do my little help, which is said they would donate all the money to the Ukrainian Red Cross.
Fear not, we are with you, the world is on your side❤️

**Comment by cachandlerdev** [comment]
Are you a Ukrainian citizen, and therefore are impacted by this issue in some way? I'm just scratching my head trying to see the connection between a KDE desktop effect plugin and a political conflict taking place in Eastern Europe. I can see that you clearly care about the subject, but I'm not sure how taking down a Linux plugin is likely to help in any way, when people probably aren't going to decide to donate based on whether this GitHub repository is up or not.

**Comment by a-parhom** [comment]
>Are you a Ukrainian citizen, and therefore are impacted by this issue in some way?
Yes, I am. And I am in Ukraine now helping my people fight russian invaders.
