### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by IT-Tagore** [a-parhom/LightlyShaders#39]
im Chinese，我想说的是，作为开发者我欣赏你的编码能力，but不要把时间全部花在学习编程语言上，而更应该学习了解历史，了解事情的来龙去脉。
1:美国一心想东扩北约，而在乌克兰的问题上，美国多次背地里制造矛盾，引发战争，还将在乌克兰布置战略设施。这威胁了俄罗斯的国土安全。

**Comment by IT-Tagore** [comment]
2:乌克兰历届亲美的总统在时任期间并没有做造福本国人民的实事。而亲俄的总统大多数都是被无故暗杀。

**Comment by IT-Tagore** [comment]
3:我不清楚你是哪国人，如果你是美国人我觉得你在推特上所看到的大多数不实的信息会误导你，煽动你的民主主义，那是毫无意义且扯淡的。

**Comment by IT-Tagore** [comment]
4：如果你是乌克兰人我理解你，你可能只是需要一个安全的生活环境。我理解你。

**Comment by IT-Tagore** [comment]
5:俄罗斯执行军事行动，并没有伤害乌克兰平民，只是摧毁了乌克兰的军事设施。

**Comment by IT-Tagore** [comment]
6:如果你不认同我说的，我也理解，在外网上，很多抹黑我们中国的，导致了全球很多人仇视歧视我们中国人，真相只有你亲历才会真相大白，中国是一个热爱和平的国家，新中国成立至今从来没有主动对别国发动战争，大多都是自卫战。而放任北约东扩，不仅俄罗斯的国土安全受到威胁，连东亚的安全也将受到威胁，so，i think，俄罗斯这场战争没有侵略，乌克兰本来就是和俄罗斯形同一家人，这完全就是帮助乌克兰人民摆脱懦夫执政，解决乌克兰人民。

**Comment by IT-Tagore** [comment]
最后我想说的是，我很喜欢你这款修复kde的插件，这使我更喜欢kde了，同时，我希望你能尽快的恢复该仓库。thanks for you

**Comment by arun54321** [comment]
"China" "Peace loving country". Thanks for the jokes.

**Comment by Hibanaw** [comment]
Never would I think a Chinese is entitled to say that the president who received 73.2% of the vote and didn't leave the front line when war broke out is a "coward".

**Comment by IT-Tagore** [comment]
> 我从来不认为一个中国人有权说，在战争爆发时获得73.2%选票而没有离开前线的总统是一个"懦夫"。

拿乌克兰的平民当挡箭牌，你的这位总统勾结外国势力，让乌克兰女性给西方卖淫，因此获得了欧洲子宫这样尊贵的称号，艾滋病率如此之高，是的，我不觉得他是个“懦夫”。我认同你。北京的小日本朋友。

**Comment by IT-Tagore** [comment]
> "China" "Peace loving country". Thanks for the jokes.
你这么说没有依据，看看你自己的国家。没亲眼看见别觉得别人再跟你开玩笑。

**Comment by Hibanaw** [comment]
> > 我从来不认为一个中国人有权说，在战争爆发时获得73.2%选票而没有离开前线的总统是一个"懦夫"。
> 
> 拿乌克兰的平民当挡箭牌，你的这位总统勾结外国势力，让乌克兰女性给西方卖淫，因此获得了欧洲子宫这样尊贵的称号，艾滋病率如此之高，是的，我不觉得他是个“懦夫”。我认同你。北京的小日本朋友。

I really regret arguing with you.
As an accelerationist, I am so glad to see your splendid talk. Just let the world see how Chinese nationalist and chauvinist are, how you claim dissidents as hostile foreign elements, and how the state-affiliated media publishes selected news.
Well, hope you have a nice day, and remind your female friends beware of kidnappers. While worrying about the women's rights in Ukraine, care more about your own people in Feng County first.

**Comment by Rayrsn** [comment]
@Hibanaw I really really respect you my dude, some people simply have been brainwashed to the point of no return, it's a really sad sight to see

**Comment by YidaozhanYa** [comment]
https://www.bilibili.com/video/BV13q4y147WZ

**Comment by weiliang1503** [comment]
> > 我从来不认为一个中国人有权说，在战争爆发时获得73.2%选票而没有离开前线的总统是一个"懦夫"。
> 
> 拿乌克兰的平民当挡箭牌，你的这位总统勾结外国势力，让乌克兰女性给西方卖淫，因此获得了欧洲子宫这样尊贵的称号，艾滋病率如此之高，是的，我不觉得他是个“懦夫”。我认同你。北京的小日本朋友。

As a Chinese, I feel really sad about your explanations. The world is so big and don't be trapped by something you are forced to see.
