### ISSUE TITLE
talk is cheap,show me your weapon

### ISSUE THREAD

**Issue by mobi12** [a-parhom/LightlyShaders#40]
If you want really help Ukraine.You can get a gun like M16 or AK47,and go to Ukraine, become a solider ,fight with enemies of human -- the Russian.But now, you delete your respository,you just make a trouble to other one,He may a American,a Russian,or Ukrainian.You like a coward,don't like a defender of the peace.

**Comment by Viohl** [comment]
People are dying, and we get to read delightful comments like these...

**Comment by askfiy** [comment]
good
