### ISSUE TITLE
Seeing multiple "-" on borders where windows intersect.

### ISSUE THREAD

**Issue by Sojiro84** [a-parhom/LightlyShaders#44]
I see this issue on X11 and Wayland.

See screenshot of what I mean. I hope the screenshots gets across what I am trying to say.

Those lines you see are at places where windows overlap. Those "-" also tend to flicker when the window updates its content.

For example, System Monitor has it blinking all the time since it refreshes it's own window a lot. With Firefox the blinking only happens when I scroll on a website. If I close or minimize the windows behind it then those "-" disappear.

It's a minor thing, but thought I'd mention it.

![IMG_0338](https://user-images.githubusercontent.com/13678578/170859619-4ab5e382-4a9f-45a3-8cf3-1c23cb0a09d4.jpeg)
![IMG_0337](https://user-images.githubusercontent.com/13678578/170859622-398d8583-79d1-4a1f-b1cb-3b47f7b87858.jpeg)

**Comment by a-parhom** [comment]
Could you, please, test if this is a regression after recent commits related to Wayland and Plasma 5.25 support, or it was present before that?

**Comment by Sojiro84** [comment]
I saw it before the recent fixes but didn't thought it was important to mention it at the time seeing as the corner issue was more important.

**Comment by a-parhom** [comment]
Ok, thank you. I'll investigate this issue.

**Comment by a-parhom** [comment]
@Sojiro84 Please, try the latest commit.

**Comment by Sojiro84** [comment]
> @Sojiro84 Please, try the latest commit.

You are a wizard. It's fixed!

**Comment by a-parhom** [comment]
Thank you! Closing.
