### ISSUE TITLE
Effect Broken When Zooming

### ISSUE THREAD

**Issue by adam-adrian** [a-parhom/LightlyShaders#46]
**Video** (Ignore the double cursor) **:**

https://user-images.githubusercontent.com/96514212/171813625-17d6d7d5-3b1d-4d04-82ba-b7f3f90a1cc4.mp4

**Comment by a-parhom** [comment]
I know about that. I've tried to fix this for a long time, but no luck so far. I've already fixed it for scaled Wayland, but not for zoom, unfortunately. Let's leave this issue open for now, maybe I'll find some solution eventually.

**Comment by adam-adrian** [comment]
Thank you! It's been already awesome at this state, and a question; how to update?

**Comment by a-parhom** [comment]
To update you just have to repeat the "Manual install" procedure from the README. That is: clone the repo (or do git pull, if it's already cloned), build and install the effect.

**Comment by adam-adrian** [comment]
Thanks. Also, can you blacklist Ulauncher?

**Comment by a-parhom** [comment]
Yes, you can open a separate issue for that. Also, I'm planning to add a blacklist functionality to settings in future.

**Comment by adam-adrian** [comment]
Ok!

**Comment by a-parhom** [comment]
Just one, for Ulauncher

**Comment by adam-adrian** [comment]
Ok
