### ISSUE TITLE
Add Blacklist Feature to Settings

### ISSUE THREAD

**Issue by adam-adrian** [a-parhom/LightlyShaders#47]
App List (Just in case there is more than one app):

Ulauncher (Because The Outline)
![Screenshot_20220603_155437](https://user-images.githubusercontent.com/96514212/171822803-d6d96687-b0db-474a-b792-0e172c755c6a.png)
![Screenshot_20220603_155444](https://user-images.githubusercontent.com/96514212/171822821-8eeeeaa5-3fb9-4038-89c4-f3424fe44f5d.png)
(Outline Strength 50%)

**Comment by a-parhom** [comment]
Ulauncher blacklisted.

**Comment by adam-adrian** [comment]
Maybe you can pin it
