### ISSUE TITLE
Seeing white line of the corner of a window (on X11 and on Wayland).

### ISSUE THREAD

**Issue by Sojiro84** [a-parhom/LightlyShaders#48]
A picture explains it better:

![IMG_0437](https://user-images.githubusercontent.com/13678578/172171564-ea32ee09-95af-4512-937d-cf4f8f039be4.jpeg)

What you see here is, I have 2 windows behind this Firefox window. From those 2 windows you can see the corner though another window (doesn't matter if it is GTK or a Qt window).

I did saw this earlier when I reported that bug with the "-" lines (https://github.com/a-parhom/LightlyShaders/issues/44), but I assumed when you fixed that one, this would also be fixed. Alas, that didn't seem to be the case.

I freshly compiled and installed the latest release before reporting to be sure to be on the most recent version.

Arch, KDE Plasma 5.24.90, fully uptodate.
AMD CPU and GPU (2700X and 5700 XT).

**Comment by a-parhom** [comment]
I'll try to fix this. No estimates for now, because it seems to be a hard one.

**Comment by Sojiro84** [comment]
> I'll try to fix this. No estimates for now, because it seems to be a hard one.

No rush.

Appreciate all that you have done so far!
