### ISSUE TITLE
Debian 11 Compile Failed

### ISSUE THREAD

**Issue by ShulkerSakura** [a-parhom/LightlyShaders#49]
After installed the packages you listed in the README it still output a lot of errors and I tried a lot of packages and libs
it is still not working
AutoMoc warning
---------------
"SRC:/lightlyshaders.cpp"
includes the moc file "lightlyshaders.moc", but does not contain a Q_OBJECT, Q_GADGET, Q_NAMESPACE, Q_NAMESPACE_EXPORT, K_PLUGIN_FACTORY, K_PLUGIN_FACTORY_WITH_JSON or K_PLUGIN_CLASS_WITH_JSON macro.

[  8%] Built target kwin4_effect_lightlyshaders_autogen
Consolidate compiler generated dependencies of target kwin4_effect_lightlyshaders
[ 16%] Building CXX object CMakeFiles/kwin4_effect_lightlyshaders.dir/kwin4_effect_lightlyshaders_autogen/mocs_compilation.cpp.o
In file included from /home/shulker/Git/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/../../../dbus.h:5,
                 from /home/shulker/Git/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/moc_dbus.cpp:10,
                 from /home/shulker/Git/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/mocs_compilation.cpp:2:
/home/shulker/Git/LightlyShaders/qt5build/kwin4_effect_lightlyshaders_autogen/EWIEGA46WW/../../../lightlyshaders.h:43:10: error: ‘void KWin::LightlyShadersEffect::prePaintWindow(KWin::EffectWindow*, KWin::WindowPrePaintData&, std::chrono::milliseconds)’ marked ‘override’, but does not override
   43 |     void prePaintWindow(EffectWindow* w, WindowPrePaintData& data, std::chrono::milliseconds time) override;
      |          ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/kwin4_effect_lightlyshaders.dir/build.make:76：CMakeFiles/kwin4_effect_lightlyshaders.dir/kwin4_effect_lightlyshaders_autogen/mocs_compilation.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:681：CMakeFiles/kwin4_effect_lightlyshaders.dir/all] 错误 2
make: *** [Makefile:146：all] 错误 2

**Comment by a-parhom** [comment]
Please, tell which Plasma version do you have?

**Comment by ShulkerSakura** [comment]
Plasma : 5.20.5
KDE Firmware : 5.78.0
QT version : 5.15.2
Kernel : 5.10.0-14

**Comment by a-parhom** [comment]
Plasma 5.20 is not supported, please see the README.
You can use previous ShapeCorners forks, like Luwx's one: https://github.com/Luwx/LightlyShaders
