### ISSUE TITLE
Outlines of windows menu are cut.

### ISSUE THREAD

**Issue by edpil02** [a-parhom/LightlyShaders#5]
When   windows menus are open  ( dolphin) ,   the corners of the menus  are rounded but we  can  see that  the outline  is cut.

**Comment by a-parhom** [comment]
Please, check out the latest changes. If the issue persists, please tell me what theme do you use, as I can't reproduce that with default Breeze as well as Kvantum with MontereyKDE theme.

**Comment by edpil02** [comment]
Thanks.
I was using native plasma theme
Here some pictures of the menu
![breeze](https://user-images.githubusercontent.com/43163048/142822491-d15a7b6a-9dca-4100-9bcf-fc54497e23b1.jpg)
![corners2](https://user-images.githubusercontent.com/43163048/142822503-36b19a7d-e7bc-4026-ba37-a34e32270c01.jpg)
s.

**Comment by edpil02** [comment]
Just built and test the latest code.
Corners seems better
![gitCorners](https://user-images.githubusercontent.com/43163048/142828674-02698e0e-969b-43ec-9868-70fd56358bd0.jpg)
.

**Comment by a-parhom** [comment]
Please try to rebuild the effect with latest changes from master branch.

**Comment by edpil02** [comment]
Thanks 
Issue fixed
