### ISSUE TITLE
Blacklist Plank dock

### ISSUE THREAD

**Issue by 123MayankSharma** [a-parhom/LightlyShaders#50]
Thanks for your work @a-parhom !
Now coming to the issue, after reading the code a little bit i found the part where you have blacklisted certain applications like albert ulauncher etc. i added a few of my own application in that list namely synapse app launcher, yakuake, guake and plank dock and then recompiled the code. It has blacklisted synapse app launcher just fine after re-compiling but plank dock seems to not have been blacklisted for some reason. it would be a great help if you could tell me how to blacklist plank dock.

I have added screenshot of the lines of code i added based on other blacklisted apps.

![image](https://user-images.githubusercontent.com/61783895/172322322-2fd14202-c82c-4273-8a9a-ac26331779c0.png)

**Comment by a-parhom** [comment]
You can try using xprop on X11 to get the right window class name of the plank dock.

**Comment by 123MayankSharma** [comment]
> You can try using xprop on X11 to get the right window class name of the plank dock.

I did the same using xprop WM_CLASS and recompiled but it still didn't get blacklisted and its causing bottom outline on windows to disappear
