### ISSUE TITLE
2.0 blur mask radius

### ISSUE THREAD

**Issue by cquasar** [a-parhom/LightlyShaders#60]
I believe 2.0 has a problem with the blur mask radius.

A screenshot to illustrate it:

![Screenshot_20220908_091839](https://user-images.githubusercontent.com/113026737/189120750-4f0068a8-f280-4eb1-b834-d0fe4a7f79d7.png)

**Comment by a-parhom** [comment]
More likely it's your decoration radius settings are not consistent with LightlyShaders. Also check that you use rounded corners instead of squircled since for now no decorations support that. I have a fork of SierraBreezeEnhanced and may be try to implement it there in future.

**Comment by cquasar** [comment]
Indeed, the problem was _Sierra Breeze Enhanced_ having a different radius size than _LightlyShaders_. Thanks for the feedback!

**Comment by TLSingh1** [comment]
Hey man, I absolutely love your work! Sorry for the dumb question.
How can I go about changing the decoration radius with breeze theme?

I suspect its in ~/.config/breezerc but I have no idea what to put and after trying so many different things, and finding nothing online regarding breezerc configs available, I'm becoming exasperated.

I've actually been here before a month or so ago and managed to edit the breeze decor radius but can't remember how and I lost the dot files (I'm dumb)! Hence my frustration

Apologies for asking a questions that's been duplicated so many times. I'd really appreciate it if you'd help a noob out. Thanks!
