### ISSUE TITLE
[Branch v2.0] Out of Place Outline Plasma Wayland

### ISSUE THREAD

**Issue by semarainc** [a-parhom/LightlyShaders#66]
Hi,
thank you for your effort on this project :D
i found problem when trying branch v2.0 

How to Reproduce:
1. Open Index-fm (file manager based on mauikit) [Need to install first], 
2. it shows outline but not in appropriate location. 
3. This only happen when enabling "outline around window" option.

Screenshot:
![image](https://user-images.githubusercontent.com/19622207/192580757-2ef22cd1-e631-4b21-b7f0-bd43af386f7a.png)

Spec Information:
Distro: Manjaro Linux
Plasma Version: 5.25.5
Display: Wayland

If you need more information, please do tell me :D
Thanks for your effort again ^_^

**Comment by semarainc** [comment]
The outline also passthrough plasma panel when doing window snap
Screenshot:
![OutlineBug](https://user-images.githubusercontent.com/19622207/192582452-dcc7dd37-6ea3-4ff5-b5dd-b5bcd818570d.png)

**Comment by xNaxdy** [comment]
Not sure if this is the same bug, but something similar happens with Firefox on 5.26 Wayland.

**Comment by semarainc** [comment]
> Not sure if this is the same bug, but something similar happens with Firefox on 5.26 Wayland.

yeah, this happen recently on my laptop with Firefox in plasma 5.25 but its less noticeable (like dropdown shadow not properly rounded)
i don't know what caused it, so i cant tell any detail about it

**Comment by a-parhom** [comment]
This is a known issue with scaled CSD windows on Wayland. Unfortunately, I don't have enough time currently to investigate this.

**Comment by xNaxdy** [comment]
> This is a known issue with scaled CSD windows on Wayland. Unfortunately, I don't have enough time currently to investigate this.

Is there any way to prevent Firefox from scaling then? I don't use any scaling on my desktop whatsoever, and every single CSD is fine except for Firefox & Thunderbird.

**Comment by zany130** [comment]
![Screenshot__3](https://user-images.githubusercontent.com/25832539/197424820-9eceba7f-e12f-46ed-b570-798b0d01af1a.png)
I think this is the same issue? only happens when I have outline around window selected with a display scale of 125%

**Comment by a-parhom** [comment]
No, it is another one. Fractional scaling is not supported at this time.

**Comment by a-parhom** [comment]
@semarainc Is the issue still present for you in v2.1?

**Comment by xNaxdy** [comment]
@a-parhom Firefox & Thunderbird under Wayland are both fixed for me in 5.27 with v2.1

**Comment by semarainc** [comment]
> @semarainc Is the issue still present for you in v2.1?

it seems i can't compile this on 5.26 ( i'm using manjaro stable), so i think i'll have to wait until manjaro update to 5.27 then i can test it :(
