### ISSUE TITLE
DecorationRadius incorrect

### ISSUE THREAD

**Issue by TLSingh1** [a-parhom/LightlyShaders#67]
Hey man, I absolutely love your work! 

Sorry for the dumb question as I've seen this duplicated numerous times, and you've already stated the solution.

How can I go about changing the decoration radius with breeze theme?

I suspect its in ~/.config/breezerc but I have no idea what to put and after trying so many different things, and finding nothing online regarding breezerc configs available, I'm becoming exasperated.

I've tried different ways to target decoration radius, in different locations like ~/.config/breezerc ~/../../usr/share/plasma/desktoptheme/breeze-dark and ~/../../usr/share/plasma/desktoptheme/breeze-light but no luck

I've actually been here before a month or so ago and managed to edit the breeze decor radius but can't remember how and I lost the dot files (I'm dumb!) Hence my frustration

I'm not sure if it's relevant but the bug only occurs when I enable Settings -> Workspace Behavior -> Desktop Effects -> Blur. The bug worsens as I increase blur strength.

Apologies for asking a questions that's been duplicated so many times. I'd really appreciate it if you'd help a noob out. Thanks!

**Comment by a-parhom** [comment]
As far as I know, default Breeze decoration has hardcoded radius at 4 or 5 px, I recommend using SierraBreezeEnhanced instead, it's much more configurable and allows to have identical to default Breeze look with the ability to change radius.
