### ISSUE TITLE
Top part of window outline is missing, when using SierraBreezeEnhanced with hidden titlebar

### ISSUE THREAD

**Issue by Peti253** [a-parhom/LightlyShaders#68]
The top part of the window outline is missing, when using SierraBreezeEnhanced with hidden titlebar with v2.0, as you can see here:

![grafik](https://user-images.githubusercontent.com/85797383/195880575-3e5da719-6c34-4ac6-ac73-8865df3ed232.png)

Plasma 5.26.0
(I had to use v2.0 because master had a compiling error. The problem didn't occur with master on plasma 5.25)

**Comment by a-parhom** [comment]
I know about this. Will return to it when I'll have some more free time.

**Comment by a-parhom** [comment]
Should be fixed in v2.1

**Comment by a-parhom** [comment]
Closing for now. If the issue persists for you, feel free to reopen.

**Comment by a-parhom** [comment]
v2.1 needs Plasma 5.26.90 (5.27).

**Comment by Peti253** [comment]
Ah okay, i currently have plasma 5.26.5 - I'll just wait for an update, thanks!
