### ISSUE TITLE
[2.0] Missing effects for menus and notifications

### ISSUE THREAD

**Issue by YidaozhanYa** [a-parhom/LightlyShaders#69]
![图片](https://user-images.githubusercontent.com/73830635/196433702-a0e9b1e9-7e7f-4589-aeee-dbfd7abd2203.png)
![图片](https://user-images.githubusercontent.com/73830635/196433774-947ba649-20b0-40ae-9e77-1af718b47abe.png)

**Comment by a-parhom** [comment]
Menus and notifications are not meant to be processed by this plugin
