### ISSUE TITLE
Swap corner radius slider for a number box

### ISSUE THREAD

**Issue by ryu-ketsueki** [a-parhom/LightlyShaders#7]
Lightly and ClassikStyles use a box to allow user to see the px value for the radius. For LightlyShaders, the only way to see the exact value is through the config file. Is it possible for the LightlyShaders configuration dialog to do the same as Lightly configuration dialog?
![Spectacle_20211122_150340](https://user-images.githubusercontent.com/39316730/142912481-32d89e14-f688-4a88-8cb1-d5b4449810d9.png)
![Spectacle_20211122_150359](https://user-images.githubusercontent.com/39316730/142912489-2f5dd7d4-74a7-4a41-bc90-71e3fb17cdc7.png)

**Comment by a-parhom** [comment]
Done in commit ef0e85bde768358cb1ec3bc9d2cf83892050c82b.
