### ISSUE TITLE
Readme : Manual installation

### ISSUE THREAD

**Issue by dahikino** [a-parhom/LightlyShaders#72]
Please make the correction of the readme :
git clone https://github.com/a-parhom/LightlyShaders
cd LightlyShaders; git checkout v2.0; mkdir qt5build; cd qt5build; cmake ../ -DCMAKE_INSTALL_PREFIX=/usr && make && sudo make install && (kwin_x11 --replace &)

**Comment by a-parhom** [comment]
It is already in README for branch v2.0. Master branch still contains the previous version and it's README reflects exactly that.
