### ISSUE TITLE
No effect and config menu since   5.26.1

### ISSUE THREAD

**Issue by edpil02** [a-parhom/LightlyShaders#73]
Config  options  disappeared  from  systemsettings  since 5.26.1 update.

Journalctl : 
 systemsettings[4287]: kf.coreaddons: KPluginFactory could not create a KDecoration2::DecorationThemeProvider instance from "/usr/lib64/qt5/plugins/org.kde.kdecoration2/lightlydecoration.so"

**Comment by a-parhom** [comment]
Try branch v2.0

**Comment by edpil02** [comment]
I'm already using v2.0  branch  . No issue with 5.26.0  only with 5.26.1.
I'm trying to figure out what has changed.

**Comment by a-parhom** [comment]
It just needs to be rebuilt then.
