### ISSUE TITLE
Issues rounding bottom corners on KDE Wayland  

### ISSUE THREAD

**Issue by linusrg1** [a-parhom/LightlyShaders#74]
For whatever reason the bottom corners of windows aren't getting rounded correctly. In GTK applications like brave, or electron apps like Cider they aren't being rounded. Same goes for some KDE apps like settings. Other KDE apps like dolphin do have rounded bottom corners, but there is still a fairly visible sharp corner around the bottom corners.

I am running the latest version of lightly, I just built it today. 

All computer specs: 

Operating System: openSUSE Tumbleweed 20221023
KDE Plasma Version: 5.26.1
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.3-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × 12th Gen Intel® Core™ i5-1240P
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: Framework
Product Name: Laptop (12th Gen Intel Core)
System Version: A4

I have a feeling this has something to do with the Intel Iris XE graphics, because I have been other small weird issues with graphical elements of the desktop, not just this. 

My External display is scaled to 125%, and my internal one 160%. I'm not sure if this matters. 

Things I have installed alongside lightly shaders: 
Utterly Round plasmashell theme
SierraBreezeEnhanced window decorations
Lightly application style

**Comment by a-parhom** [comment]
Fractional scaling is not supported at the moment, sorry.

**Comment by a-parhom** [comment]
Scaling is working good now in Plasma 6 with plasma6 branch (Wayland).
