### ISSUE TITLE
Not working on titlebars

### ISSUE THREAD

**Issue by ericmacedo** [a-parhom/LightlyShaders#77]
![image](https://user-images.githubusercontent.com/8262322/199759465-0fbd429f-81e5-4704-a94b-f1ab8ced74d6.png)
![image](https://user-images.githubusercontent.com/8262322/199759556-9d9ca70f-b021-48aa-8739-8dfcc97ade4e.png)

I've tested it in branch master, v2.0, X11, and Wayland.
It happens with any window decoration.

Other applications without KDE's window decoration don't seem to have this problem:
![image](https://user-images.githubusercontent.com/8262322/199764630-e98638a8-8d06-48d9-9db4-01700f9e5628.png)

Specs:
- OS: Manjaro 22.0.0 Sikaris
- Kernel: x86_64 Linux 5.15.76-1-MANJARO
- DE: KDE 5.99.0 / Plasma 5.26.2
- WM: KWin (X11)
- Kvantum Manager: 1.0.6
- Window decoration: [BreezeEnhanced](https://github.com/tsujan/BreezeEnhanced)
- Plasma theme: [WhiteSur](https://github.com/vinceliuice/WhiteSur-kde)

**Comment by a-parhom** [comment]
This is intended behavior because of "korner" bug. Because of the way how the blur effect is designed now, only window decorations can deal with it, so you should configure radius in your decoration to match LightlyShaders. That is not the case with CSD windows though.
