### ISSUE TITLE
Effect not working

### ISSUE THREAD

**Issue by ramon501** [a-parhom/LightlyShaders#79]
Not sure if it's just on my end, but at least for me it stopped working, i switched to the aur package, tried reinstalling it and nothing
plasmashell 5.26.3
effect shows if i uncheck "Exclude unsupported effects"

**Comment by a-parhom** [comment]
Install from branch v2.0, it supports plasma 5.26. It also needs your GPU to support newer OpenGL though.

**Comment by ramon501** [comment]
That worked for me, i uninstalled the aur package and built the effect manually, i thought the aur package was using the v2.0 branch and that it would work since it's git, thanks for the support

**Comment by alexjp** [comment]
if I am not mistaken, is because the kwin plugin doesn't install on the proper place.

it seems to install `kwin/effects/plugins/kwin4_effect_lightlyshaders.so` to root ( / )

**Comment by a-parhom** [comment]
2.0 code is in master branch now.
