### ISSUE TITLE
Maximized windows are rounded

### ISSUE THREAD

**Issue by ObmijSelaw** [a-parhom/LightlyShaders#8]
Basically what the title says. I'm not sure if it's intended that the windows are still rounded when maximized. In the attached screenshot, the bottom left and bottom right corners are rounded. If it's intended, I suggest adding an option to disable rounding on maximized windows.

Here's some info about my system:
OS: KDE neon 5.23 User Edition
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.3
Kernel Version: 5.15.5-xanmod1-tt (64 bit)
Graphics platform: X11

Thanks for all the work, even with this problem, I find that your fork is the most mature rounded corner implementation for KWin.
![Screenshot_20211125_214446](https://user-images.githubusercontent.com/81539176/143524916-f446a193-0547-4881-a2d6-2164c3e393d5.png)

**Comment by a-parhom** [comment]
Added an option to disable the effect for maximized windows in commit 0469c48cce6e89678d88afa6b99b500700f0bb04.
