### ISSUE TITLE
Error while installing on KDE Neon 5.26

### ISSUE THREAD

**Issue by lethinhrider** [a-parhom/LightlyShaders#82]
Hi, I got an error when I ran the command even though I followed the instructions at the README page correctly.
I don't know how to describe the error so I'll include the output file for you to read:
[output1.txt](https://github.com/a-parhom/LightlyShaders/files/10088580/output1.txt)

**More information**
Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 6.0.9-x64v1-xanmod1 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 3.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
Manufacturer: ASUSTeK COMPUTER INC.
Product Name: X541UAK
System Version: 1.0

**Comment by ChrisCochrun** [comment]
Your error looks like you are trying to install the master branch and that doesn't compile on 5.26. I tried for a long time, it just won't. You need to switch to the v2.0 branch and then try to compile.

**Comment by lethinhrider** [comment]
> Your error looks like you are trying to install the master branch and that doesn't compile on 5.26. I tried for a long time, it just won't. You need to switch to the v2.0 branch and then try to compile.

It shows even more serious error: 
[output2.txt](https://github.com/a-parhom/LightlyShaders/files/10154930/output2.txt)

**Comment by Goodname15** [comment]
You need to install "libkdecorations2-dev" (could be wrong, I'm using Fedora and for me the package was "kdecoration-devel")
