### ISSUE TITLE
What is needed for fractional scaling support?

### ISSUE THREAD

**Issue by ChrisCochrun** [a-parhom/LightlyShaders#83]
Basically the question. I looked through the codebase and I can't seem to figure out how that would get implemented basically. Is it an upstream issue?

**Comment by a-parhom** [comment]
Factional scaling is tricky, and there are some fundamental changes planned for Plasma 5.27, so I'd like for it to settle down first, after that I'll start tinkering with it. 

For now I'm focused on merging this effect with Sierra Breeze Enhanced window decoration. This will allow us to configure both decoration and rounding effect in one place, as well as use window rules for applying different settings for different windows.

**Comment by ChrisCochrun** [comment]
That'd be awesome since I am using sierra breeze enhanced. Also, just wanted to say, since I made this thread, I did hear about the Plasma 5.27 changes coming, and think you are wise to wait for that. It will likely make it a lot easier using Plasma's fractional scaling bits. Looking forward to it as it's the only thing that sometimes entices me to a standalone WM instead of plasma.

Also, just nice work man. I really like this project!

**Comment by a-parhom** [comment]
You can try the merged with window decoration effect here: https://github.com/a-parhom/RoundedSBE
It is still in development and may not work for you, some features are missing. But it works for me on X11.

**Comment by SqrHornet** [comment]
Hey, I just wanted to ask if the problem I'm facing here is related to this. I am using custom DPI (know it's not recommended, but let's just say that per 12,5% scalling is a bit too much). I was using this effect before and it wasn't happening:
![2023-01-27_22-50](https://user-images.githubusercontent.com/84623999/215208358-50ea2d5f-88a7-4185-aa7d-636882c73375.png)

**Comment by a-parhom** [comment]
@SqrHornet Looks like the window decoration is not compatible. Try RoundedSBE, it's a SierraBreezeEnhanced decoration with integrated LightlyShaders to it.

**Comment by schyhub** [comment]
Just want to add it here, on my laptop with a high dpi screen 1600p (16:10 -13.x in), since 5.27, and till now with latest Lightlyshaders, there is correct borders and no artifacts when I use 1.5x scaling. Used to be a mess on 5.26.

**Comment by a-parhom** [comment]
Scaling works good now with plasma6 branch. Also, no specific window decorations are needed.
