### ISSUE TITLE
Titlebar buttons highlight/active effect not working correctly on Plasma 5.26.90

### ISSUE THREAD

**Issue by luisbocanegra** [a-parhom/LightlyShaders#87]
When LightlyShaders is enabled the highlight when hovering titlebar buttons starts behaving slower or doesn't work at all most of the time, this happens on both X11 and Wayland session.

https://user-images.githubusercontent.com/15076387/213962599-e92f7de9-0f04-4545-b810-9131165fca0d.mp4

**System details:**
Operating System: Arch Linux 
KDE Plasma Version: 5.26.90
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.7-arch1-1 (64-bit)
Graphics Platform: X11
Graphics Processor: Mesa Intel® UHD Graphics 630

**Comment by a-parhom** [comment]
This is Plasma bug

**Comment by a-parhom** [comment]
Let it be open for now.

**Comment by a-parhom** [comment]
The upstream bug: https://bugs.kde.org/show_bug.cgi?id=464417

**Comment by ramon501** [comment]
i have this issue now that i updated to plasma 5.27.0

**Comment by a-parhom** [comment]
It is a Plasma bug, not LightlyShaders.

**Comment by a-parhom** [comment]
Going to be fixed in Plasma 5.27.1: https://invent.kde.org/plasma/kwin/-/merge_requests/3634

**Comment by toxic-candy** [comment]
Fixed with Plasma 5.27.1

**Comment by ramon501** [comment]
working nice to me after updating to plasma 5.27.1
