### ISSUE TITLE
Effect doesn't apply all the time to popups

### ISSUE THREAD

**Issue by gianmarcogg03** [a-parhom/LightlyShaders#9]
I'm using Plasma 5.23.3 on Arch Linux and the shader 9 times out of 10 does not work on shell popups (window thumbnails, system tray, tooltips, etc.).
![2021-11-26_17-58](https://user-images.githubusercontent.com/28053717/144485987-11d6fe83-8ae5-4a51-a628-2bf1f82c8851.png)
![2021-11-26_18-01](https://user-images.githubusercontent.com/28053717/144486001-85cc62c7-6f7b-484f-81d8-7f5050475a7a.png)

**Comment by a-parhom** [comment]
Well, it is not supposed to ever work on that. 
So, the bug is that it works, not that it does not. Maybe there is some  ​kind of race condition or sometheing because of which the effect does not reject those popups 1 time of 10. I'll look into it when I'll have some spare time.

**Comment by a-parhom** [comment]
The "performance_optimizations" branch has the fix for this issue. You can try that right now or wait for the branch being merged to master after some more testing and polishing.
