### ISSUE TITLE
using on kwin git (nightly), makes kwin on wayland crash

### ISSUE THREAD

**Issue by alexjp** [a-parhom/LightlyShaders#90]
Hi, thanks for the wonderfull effect!

I am using kwin git nightly versions, and between kwin commit: `b712c26457a61c4ff46c7efbc27acc245ddbf5cf` and `1746af4b0299b77e17efb6d0d8574cebc199b544`, lightlyshaders is making kwin crash.

removing lightlyshaders effects make kwin not crash.

Thanks you for your work!

**Comment by a-parhom** [comment]
Have you recompiled LightlyShaders after update?

**Comment by alexjp** [comment]
> Have you recompiled LightlyShaders after update?

.... No, i didn't.

I did now, and it works properly. Sorry for opening this bad issue and taking your time! :(
