### ISSUE TITLE
How to remove this software from KDE

### ISSUE THREAD

**Issue by adipginting** [a-parhom/LightlyShaders#91]
Hello, sorry if this is a novice question, but what is the proper way to uninstall this application? I searched and deleted all files with the name of lightlyshaders under /usr, but I am not sure if that is enough to remove all of the installed files. 

Thanks.

**Comment by a-parhom** [comment]
The `install_manifest.txt` in the qt5build folder lists all the installed files.
Also, running `sudo make uninstall`  in that folder will uninstall the plugin.
