### ISSUE TITLE
Rounding effect no longer seems to ignore window decorations, which breaks outlines.

### ISSUE THREAD

**Issue by Void-0000** [a-parhom/LightlyShaders#95]
I just updated from the v2.0 branch to master, previously in v2.0 the effect didn't cut out window decorations, but now it seems like it does, which breaks any kind of window decoration provided outline, like this:

![image](https://user-images.githubusercontent.com/44403167/221671620-d81e3e17-9b3e-4dd9-ae1b-4e84b22058e7.png)

Before the outline would go around the rounded corner properly, is there a way to get that to work again?

**Comment by a-parhom** [comment]
This effect is meant to be used without borders.

**Comment by Void-0000** [comment]
I'm aware, but this is with my window decorations set to borderless. Some window decorations have window outlines built-in, like Klassy and Breeze.
These used to work great on the v2.0 branch, what changed?

**Comment by a-parhom** [comment]
Plasma 5.27 forces to uses different approach to rounding. You can use SierraBreezeEnhanced or RoundedSBE.

**Comment by a-parhom** [comment]
Not with Plasma 5.27 and onwards.

**Comment by a-parhom** [comment]
LightlyShaders has builtin outline, by the way.

**Comment by Void-0000** [comment]
Oh, I see. Unfortunately the built-in outline doesn't really do what I'm looking for, Klassy's outline changes color based on highlighted buttons and such, which I thought was a really neat feature.
Too bad, then. Thanks anyway.

**Comment by Void-0000** [comment]
> This is the reason I'm still using the v2.0 branch, since I really like Klassy's outline
> 
> Reverted the patches in KWin ([here](https://github.com/luisbocanegra/kwin-lightlyshaders-compatible/tree/lightlyshaders-changes)) that broke LightlyShaders v2.0 and seems to run fine, at least for now...

I more or less know nothing about how KDE stuff works internally, so this might be a bit of a dumb question, but do the patches break v2.0 intentionally or is it a bug? Basically I'm asking if we'll have to keep using a forked version of kwin forever or if it might get fixed eventually.
Alternatively, would it be possible to adapt v2.0 instead of reverting the changes in kwin?

**Comment by luisbocanegra** [comment]
> > This is the reason I'm still using the v2.0 branch, since I really like Klassy's outline
> > Reverted the patches in KWin ([here](https://github.com/luisbocanegra/kwin-lightlyshaders-compatible/tree/lightlyshaders-changes)) that broke LightlyShaders v2.0 and seems to run fine, at least for now...
> 
> I more or less know nothing about how kwin or desktop effects work, 

I'm on the same boat, sadly

> so this might be a bit of a dumb question, but do the patches break v2.0 intentionally or is it a bug? Basically I'm asking if we'll have to keep using a forked version of kwin forever or if it might get fixed eventually.

AFAIK they're intentional changes, I don't remember @a-parhom mentioning otherwise and the commit messages don't suggest that either. Personally, I'll keep using it while still works and will probably switch to LightlyShaders outline when it no longer does and I cannot figure out a way to make it work 🥲

> Alternatively, would it be possible to adapt v2.0 instead of reverting the changes in kwin?

I think it can be adapted to one of the commits (the blur region one) but not for the other. But @a-parhom knows better when they say it isn't possible...

After all, I'm thankful for all the effort they have put into this effect ❤️ and hope that one day we get something like this natively in KWin..

**Comment by a-parhom** [comment]
I think, outline colors can be introduced in future, maybe in the RoundedSBE first, though.

**Comment by Void-0000** [comment]
So, I'm absolutely no expert on this, but I've been looking through the Klassy window decoration's code and as far as I can tell the outline is drawn _as part of the shadow_, so how come it gets removed by LightlyShaders when the rest of the shadow doesn't? Does LightlyShaders re-draw its own shadow now or does it still use the window decoration's shadow like in v2.0?
I'm hoping that if I can figure out what that difference is, I can make the outline fully part of the shadow so LightlyShaders no longer removes it.

**Comment by a-parhom** [comment]
The shadow is interpolated now as in v1.0.
