### ISSUE TITLE
Windows become blurry when dragging from the toolbar or CSD in Wayland.

### ISSUE THREAD

**Issue by ThakshilaDamsak** [a-parhom/LightlyShaders#96]
When Lightlyshaders are enabled in Wayland, windows become blurry when dragging it from the toolbar or CSD. However, dragging it from the title bar removes the blurriness and the window becomes normal again. Unfortunately, CSD applications need to be closed and reopened to remove blurriness. Is this a bug in Lightlyshaders, or am I doing something wrong?

KDE Plasma Version: 5.27.1
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Graphics Processor: Mesa Intel® HD Graphics 520

https://user-images.githubusercontent.com/95128171/222397187-b9d5a303-698b-4755-bf1b-87ef76526606.mp4

**Comment by a-parhom** [comment]
Do you use hidpi scaling?

**Comment by a-parhom** [comment]
Also, could you, please, check if you will have this issue with the Plasma's Invert effect (LightlyShaders should be disabled). If you will experience the issue, it means the bug is in Plasma's effects API. Otherwise it's LightlyShaders bug.

**Comment by ThakshilaDamsak** [comment]
I am not using hidpi scaling. It happens with the invert effect. So it's not a LighlyShaders bug. Thank you!

**Comment by a-parhom** [comment]
Then please open a kde bug report, so that the devs were aware and could fix it.

**Comment by ThakshilaDamsak** [comment]
I found out it was a config file issue on my user account. Deleting the kwinrc config file solved the issue. I've also reported this to KDE bugtracking system: https://bugs.kde.org/show_bug.cgi?id=466822.

Apologies for any confusion.
