### ISSUE TITLE
Wayland: Windows with blur have a "korner" bug on the bottom

### ISSUE THREAD

**Issue by xNaxdy** [a-parhom/LightlyShaders#99]
This issue is mentioned in the readme already, but I figure it's not a bad idea to have it tracked.

Question: What would be needed in order to fix this issue? I understand that upstream would need to provide an API to adjust the blur region, but what exactly is necessary for that and where would it need to be exposed?

If I know this, I'd have a crack at potentially implementing it in kwin.

**Comment by a-parhom** [comment]
It  is already implemented (https://invent.kde.org/plasma/kwin/-/merge_requests/3407), but the devs have contradicting opinions on this feature.

**Comment by xNaxdy** [comment]
I see, thanks for the pointer! Will keep an eye on the MR.

**Comment by a-parhom** [comment]
Looks like themes such as Lightly can fix this issues by setting the corner radius by themselves (though Lightly itself needs some patching, because it lets using maximum radius of 6px only)

**Comment by a-parhom** [comment]
This is supposed to be fixed in plasma6 branch.

**Comment by a-parhom** [comment]
The branch has forked blur effect included, that fixes the "korner" bug.
